# Generated by Django 5.2.5 on 2026-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlxDataXml',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=200, null=True)),
                ('no_concepto', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_prod_serv', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_unidad', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_unitario', models.FloatField(blank=True, null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('impuesto', models.FloatField(blank=True, null=True)),
                ('tipo_factor', models.CharField(blank=True, max_length=100, null=True)),
                ('tasa_cuota', models.FloatField(blank=True, null=True)),
                ('importe_imp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vlx_data_xml',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VlxSatCfdiRaw',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('xmlcontent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('void_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'vlx_sat_cfdi_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VlxSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=200, null=True)),
                ('rfc_emisor', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_emisor', models.CharField(blank=True, max_length=200, null=True)),
                ('regimen_fiscal', models.CharField(blank=True, max_length=200, null=True)),
                ('rfc_receptor', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_receptor', models.CharField(blank=True, max_length=200, null=True)),
                ('uso_cfdi', models.CharField(blank=True, max_length=200, null=True)),
                ('schema_location', models.CharField(blank=True, max_length=200, null=True)),
                ('uuid_fiscal', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('rfc_prov_certif', models.CharField(blank=True, max_length=200, null=True)),
                ('sello_cfd', models.CharField(blank=True, max_length=200, null=True)),
                ('no_certificado_sat', models.CharField(blank=True, max_length=200, null=True)),
                ('sello_sat', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'vlx_suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VlxTotalDataXml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=150, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('base_iva', models.FloatField(blank=True, db_column='base_IVA', null=True)),
                ('importe', models.FloatField(blank=True, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=5, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=5, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vlx_total_data_xml',
                'managed': False,
            },
        ),
    ]
